version: "3"
services:
    cli:
        build:
            context: ./
            dockerfile: ./docker/dev/cli/Dockerfile
        volumes:
            - ./:/var/www/app
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        tty: true
        restart: always

    mysql:
        image: mysql:8.0.30
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123123"
            - "MYSQL_DATABASE=test-task"
            - "MYSQL_USER=test-user"
            - "MYSQL_PASSWORD=123123"
        ports:
            - "33061:3306"
        tty: true
        restart: always

    php-fpm:
        build:
            context: ./
            dockerfile: ./docker/dev/php-fpm/Dockerfile
        volumes:
            - ./:/var/www/app
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        depends_on:
            - mysql
        restart: always

    nginx:
        build:
            context: ./
            dockerfile: ./docker/dev/nginx/Dockerfile
        volumes:
            - ./web:/var/www/app/web
        ports:
            - "80:80"
        depends_on:
            - php-fpm
        restart: always

