PUT http://localhost/api/tasks/1/done HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "done": true
}

###
PUT http://localhost/api/tasks/1/done HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "done": false
}

###
GET http://localhost/api/tasks/1 HTTP/1.1
Accept: application/json
